apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    name: frontend-svc
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: frontend-port
  selector:
     app: web-iot-isnow
     tier: front-end